name: 🐛 Bug Report
description: Report issues with GitHub Actions workflow
title: "[ACTION BUG]: "
labels: ["bug", "github-actions"]
body:
  - type: markdown
    attributes:
      value: |
        Describe an issue with our GitHub Action!

  - type: textarea
    id: error_output
    attributes:
      label: Error Output
      description: Please provide the GitHub Actions error output
      render: shell
    validations:
      required: true

  - type: input
    id: action_issue_url
    attributes:
      label: Coresponding Action Issue
      description: Link to the issue in the action repository
      placeholder: "https://github.com/XXX"
    validations:
      required: true

  - type: input
    id: mode_name
    attributes:
      label: Model Name
      description: Which model are you converting?
      placeholder: Huggingface URL of the model
    validations:
      required: true

  - type: input
    id: llama_issue_ref
    attributes:
      label: Related llama.cpp Issue/PR
      description: Find related llama.cpp issue or PR to the model you are converting
      placeholder: "https://github.com/ggerganov/llama.cpp/issues/XXX"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Custom build flags used
        - Modified parameters
        - System specifications
        - Any other relevant information